// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductManagement.Infrastructure;

#nullable disable

namespace ProductManagement.Infrastructure.Migrations
{
    [DbContext(typeof(ProductManagementDbContext))]
    [Migration("20251101215853_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ProductManagement.Domain.Categories.Category", b =>
                {
                    b.Property<Guid>("AggregateId")
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("AggregateId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ProductCount");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("ProductManagement.Domain.Orders.Order", b =>
                {
                    b.Property<Guid>("AggregateId")
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("AggregateId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("ProductManagement.Domain.Products.Product", b =>
                {
                    b.Property<Guid>("AggregateId")
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("AggregateId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedAt");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("ProductManagement.Domain.Orders.Order", b =>
                {
                    b.OwnsMany("ProductManagement.Domain.Orders.OrderItem", "Items", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("OrderId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("ProductId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ProductName")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("Quantity")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Id", "OrderId");

                            b1.HasIndex("OrderId");

                            b1.ToTable("OrderItems", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("OrderId");

                            b1.OwnsOne("ProductManagement.Domain.Products.ValueObjects.Money", "UnitPrice", b2 =>
                                {
                                    b2.Property<Guid>("OrderItemId")
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid>("OrderItemOrderId")
                                        .HasColumnType("TEXT");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("UnitPriceAmount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("UnitPriceCurrency");

                                    b2.HasKey("OrderItemId", "OrderItemOrderId");

                                    b2.ToTable("OrderItems");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderItemId", "OrderItemOrderId");
                                });

                            b1.Navigation("UnitPrice")
                                .IsRequired();
                        });

                    b.Navigation("Items");
                });

            modelBuilder.Entity("ProductManagement.Domain.Products.Product", b =>
                {
                    b.OwnsOne("ProductManagement.Domain.Products.ValueObjects.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("ProductAggregateId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("PriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("PriceCurrency");

                            b1.HasKey("ProductAggregateId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductAggregateId");
                        });

                    b.OwnsOne("ProductManagement.Domain.Products.ValueObjects.Stock", "Stock", b1 =>
                        {
                            b1.Property<Guid>("ProductAggregateId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Quantity")
                                .HasColumnType("int")
                                .HasColumnName("StockQuantity");

                            b1.Property<int>("ReservedQuantity")
                                .HasColumnType("int")
                                .HasColumnName("StockReservedQuantity");

                            b1.HasKey("ProductAggregateId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductAggregateId");
                        });

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("Stock")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
